### ISSUE TITLE
Support for lightweight tags

### ISSUE THREAD

**Issue by kennethjor** [DanySK/git-sensitive-semantic-versioning-gradle-plugin#323]
[Semantic Release](https://github.com/semantic-release/semantic-release) doesn't support creating annotated tags, but this plugin seems to require it. It's be nice to be able to configure it either way, or to just use any tag. Would that be possible?

I had a look at the history over there and even saw a comment by you @DanySK (though I can't find it now). It seems they used to support it, but it was reverted.

**Comment by kennethjor** [comment]
It looks like this can be implemented with `git describe --tags` instead of `git describe`. Though I admit I'm not intimately familiar with how the plugin is set up.

**Comment by DanySK** [comment]
This is definitely something I want to support, too. I would gladly review a pull request, but implementing it myself will take weeks (it is a matter of few hours, but I currently spare close to no time for my personal projects).

It should be something like:
```kotlin
gitSemVer {
    includeLightweightTags()
}
```

Meanwhile, please consider configuring semantic-release to generate annotated tags -- namely, force semantic release into generating them. This plugin uses semantic release as well, and [this is the configuration](https://github.com/DanySK/git-sensitive-semantic-versioning-gradle-plugin/blob/27c88a6d5a9fef8001d5136cd525d1f459db00dd/release.config.js).

**Comment by DanySK** [comment]
Fixed by #457. Support will be mainlined soon.
