### ISSUE TITLE
Usage of Runtime.exec() breaks configuration cache

### ISSUE THREAD

**Issue by maksym-moroz** [DanySK/git-sensitive-semantic-versioning-gradle-plugin#676]
[Here](https://docs.gradle.org/8.2/userguide/configuration_cache.html#config_cache:requirements:external_processes) is the explanation in the gradle docs.

It should be possible to switch to ExecOperation for query of git in external process.

**Comment by maksym-moroz** [comment]
@DanySK fyi, I prepared a PR to address the issue but I am unable to push it as I am not authorised to create a separate branch for PR. Let me know how to proceed

**Comment by DanySK** [comment]
Thanks!

@maksym-moroz, do as follows:
1. fork this repo into your personal space https://github.com/DanySK/git-sensitive-semantic-versioning-gradle-plugin/fork
2. push the branch to your copy of this repo
3. open a PR from your fork's branch to my fork's `master`

**Comment by maksym-moroz** [comment]
@DanySK, let me know what you think. Happy to collaborate further to get this done.

**Comment by DanySK** [comment]
The pull request has been merged. Reopen if something is wrong.

Thank you for the contribution, very appreciated :bow:
